# Generated by Django 3.0.3 on 2020-02-11 07:47

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=1000, unique=True)),
                ('Year', models.CharField(max_length=1000)),
                ('Rated', models.CharField(max_length=1000)),
                ('Released', models.CharField(max_length=1000)),
                ('Runtime', models.CharField(max_length=1000)),
                ('Genre', models.CharField(max_length=1000)),
                ('Director', models.CharField(max_length=1000)),
                ('Writer', models.CharField(max_length=1000)),
                ('Actors', models.CharField(max_length=1000)),
                ('Plot', models.CharField(max_length=1000)),
                ('Language', models.CharField(max_length=1000)),
                ('Country', models.CharField(max_length=1000)),
                ('Awards', models.CharField(max_length=1000)),
                ('Poster', models.CharField(max_length=1000)),
                ('Ratings', models.CharField(max_length=1000)),
                ('Metascore', models.IntegerField()),
                ('imdbRating', models.FloatField(max_length=1000)),
                ('imdbVotes', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('imdbID', models.CharField(max_length=1000)),
                ('Type', models.CharField(max_length=1000)),
                ('DVD', models.CharField(max_length=1000)),
                ('BoxOffice', models.CharField(max_length=1000)),
                ('Production', models.CharField(max_length=1000)),
                ('Website', models.CharField(max_length=1000)),
                ('Response', models.CharField(max_length=1000)),
            ],
        ),
    ]
