# Generated by Django 3.0.3 on 2020-02-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=1000)),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapi.Details')),
            ],
        ),
    ]
